### ISSUE TITLE
ConcatenatedBytes bug

### ISSUE THREAD

**Issue by Nashatyrev** [apache/incubator-tuweni#186]
Tuweni version `1.1.0`

Legitimate test case
```java
    Bytes concatBytes = Bytes.wrap(
        Bytes.wrap(
            Bytes.wrap(new byte[32]),
            Bytes.wrap(new byte[6])
        ).slice(0, 37),
        Bytes.wrap(new byte[1]));
    byte[] bytes = concatBytes.toArrayUnsafe();
```

throws 

```
java.lang.IllegalStateException: element sizes do not match total size
	at org.apache.tuweni.bytes.ConcatenatedBytes.copyToUnchecked(ConcatenatedBytes.java:206)
	at org.apache.tuweni.bytes.ConcatenatedBytes.toArray(ConcatenatedBytes.java:197)
	at org.apache.tuweni.bytes.Bytes.toArrayUnsafe(Bytes.java:1420)
```

**Comment by Nashatyrev** [comment]
I believe this is a closely related case: 
```java
    Bytes.concatenate(
        Bytes.wrap(
            Bytes.wrap(new byte[32]),
            Bytes.wrap(new byte[6])
        ).slice(0, 37),
        Bytes.wrap(new byte[1]));
```

throws the exception:
```
java.lang.IllegalStateException: element sizes do not match total size
	at org.apache.tuweni.bytes.ConcatenatedBytes.copyToUnchecked(ConcatenatedBytes.java:206)
	at org.apache.tuweni.bytes.ConcatenatedBytes.copyTo(ConcatenatedBytes.java:187)
	at org.apache.tuweni.bytes.Bytes.concatenate(Bytes.java:126)
```

**Comment by Nashatyrev** [comment]
More localized testcase: 
```java
Bytes.wrap(
        Bytes.wrap(new byte[32]),
        Bytes.wrap(new byte[6])
    ).slice(0, 37).copy()
```
throws: 
```
java.lang.IllegalStateException: element sizes do not match total size
	at org.apache.tuweni.bytes.ConcatenatedBytes.copyToUnchecked(ConcatenatedBytes.java:206)
	at org.apache.tuweni.bytes.ConcatenatedBytes.copy(ConcatenatedBytes.java:159)
```

**Comment by atoulme** [comment]
Thanks, looking.

**Comment by atoulme** [comment]
Fixed, thank you for reporting. Time to get 1.4.0 out soon.
