### ISSUE TITLE
Exception reading DisconnectMessage

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#268]
```
07:00:06.757 [vert.x-eventloop-thread-1] ERROR org.apache.tuweni.rlpx.vertx.VertxRLPxService - Attempted to read a list but next item is a value
org.apache.tuweni.rlp.InvalidRLPTypeException: Attempted to read a list but next item is a value
        at org.apache.tuweni.rlp.BytesRLPReader.readList(BytesRLPReader.java:220)
        at org.apache.tuweni.rlp.BytesRLPReader.readList(BytesRLPReader.java:114)
        at org.apache.tuweni.rlp.RLPReader.readList(RLPReader.java:285)
        at org.apache.tuweni.rlp.RLP.lambda$decodeList$1(RLP.java:302)
        at org.apache.tuweni.rlp.RLP.decode(RLP.java:270)
        at org.apache.tuweni.rlp.RLP.decodeList(RLP.java:302)
        at org.apache.tuweni.rlp.RLP.decodeList(RLP.java:284)
        at org.apache.tuweni.rlpx.wire.DisconnectMessage.read(DisconnectMessage.java:31)
        at org.apache.tuweni.rlpx.wire.DefaultWireConnection.messageReceived(DefaultWireConnection.java:174)
        at org.apache.tuweni.rlpx.RLPxConnection.stream(RLPxConnection.java:150)
        at org.apache.tuweni.rlpx.vertx.VertxRLPxService$2.handle(VertxRLPxService.java:375)
        at org.apache.tuweni.rlpx.vertx.VertxRLPxService$2.handle(VertxRLPxService.java:338)
        at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:376)
        at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
        at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:356)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:164)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by atoulme** [comment]
Fixed with #292
