### ISSUE TITLE
Discovery: handle invalid secp256k1 keys

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#269]
```
07:00:14.923 [DefaultDispatcher-worker-1] ERROR org.apache.tuweni.devp2p.DiscoveryService - ÐΞVp2p discovery 1159675056: unexpected error during packet handling
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid point coordinates
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
        at org.apache.tuweni.devp2p.DevP2PPeerRoutingTable.hashForId(PeerRoutingTable.kt:100)
        at org.apache.tuweni.devp2p.DevP2PPeerRoutingTable.nearest(PeerRoutingTable.kt:92)
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService.neighbors(DiscoveryService.kt:863)
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService.handleFindNode(DiscoveryService.kt:610)
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService$handleFindNode$1.invokeSuspend(DiscoveryService.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: Invalid point coordinates
        at org.bouncycastle.math.ec.ECCurve.validatePoint(ECCurve.java:125)
        at org.bouncycastle.math.ec.ECCurve.decodePoint(ECCurve.java:418)
        at org.apache.tuweni.crypto.SECP256K1$PublicKey.asEcPoint(SECP256K1.java:707)
        at org.apache.tuweni.devp2p.EthereumNodeRecord$Companion.nodeId(EthereumNodeRecord.kt:58)
        at org.apache.tuweni.devp2p.DevP2PPeerRoutingTable$hashForId$1.call(PeerRoutingTable.kt:100)
        at org.apache.tuweni.devp2p.DevP2PPeerRoutingTable$hashForId$1.call(PeerRoutingTable.kt:69)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        ... 16 common frames omitted
```

**Comment by atoulme** [comment]
This is now implemented as part of checking the execution here:
```
  private fun hashForId(id: SECP256K1.PublicKey): ByteArray? {
    try {
      return idHashCache.get(id) { EthereumNodeRecord.nodeId(id).toArrayUnsafe() }
    } catch (e: UncheckedExecutionException) {
      if (e.cause is IllegalArgumentException) {
        return null
      }
      throw e
    }
  }
```

Closing as complete.
