### ISSUE TITLE
NPE reported during discovery interaction cancellation

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#270]
```
07:00:49.866 [DefaultDispatcher-worker-1] ERROR org.apache.tuweni.devp2p.DiscoveryService - ÐΞVp2p discovery 1159675056: unexpected error during packet handling
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.apache.tuweni.devp2p.CoroutineDiscoveryService$lookup$3$invokeSuspend$$inlined$map$lambda$1$1.invoke, parameter a
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService$lookup$3$invokeSuspend$$inlined$map$lambda$1$1.invoke(DiscoveryService.kt)
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService$lookup$3$invokeSuspend$$inlined$map$lambda$1$1.invoke(DiscoveryService.kt:290)
        at org.apache.tuweni.kademlia.KademliaRoutingTableKt$orderedInsert$i$1.invoke(KademliaRoutingTable.kt:75)
        at org.apache.tuweni.kademlia.KademliaRoutingTableKt$orderedInsert$i$1.invoke(KademliaRoutingTable.kt)
        at kotlin.collections.CollectionsKt__CollectionsKt.binarySearch(Collections.kt:425)
        at kotlin.collections.CollectionsKt__CollectionsKt.binarySearch$default(Collections.kt:416)
        at org.apache.tuweni.kademlia.KademliaRoutingTableKt.orderedInsert(KademliaRoutingTable.kt:75)
        at org.apache.tuweni.devp2p.CoroutineDiscoveryService$lookup$3$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(DiscoveryService.kt:475)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: java.lang.NullPointerException: Parameter specified as non-null is null: method org.apache.tuweni.devp2p.CoroutineDiscoveryService$lookup$3$invokeSuspend$$inlined$map$lambda$1$1.invoke, parameter a
                ... 14 common frames omitted

```

**Comment by atoulme** [comment]
Closing, will reopen if I see it again.
