### ISSUE TITLE
Vert.x thread blocked when negotiating many handshakes

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#272]
When trying to connect to many nodes at once (over 100) on a t3.large with some constraints on CPU, I see this warning:

```
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5110 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
        at java.base@14.0.2/java.math.BigInteger.multiply(BigInteger.java:1601)
        at java.base@14.0.2/java.math.BigInteger.multiply(BigInteger.java:1567)
        at app//org.bouncycastle.math.ec.ECFieldElement$Fp.modMult(ECFieldElement.java:432)
        at app//org.bouncycastle.math.ec.ECFieldElement$Fp.multiply(ECFieldElement.java:182)
        at app//org.bouncycastle.math.ec.ECPoint$Fp.twiceJacobianModified(ECPoint.java:1329)
        at app//org.bouncycastle.math.ec.ECPoint$Fp.twice(ECPoint.java:999)
        at app//org.bouncycastle.math.ec.ECPoint$Fp.timesPow2(ECPoint.java:1152)
        at app//org.bouncycastle.math.ec.ECAlgorithms.implShamirsTrickWNaf(ECAlgorithms.java:385)
        at app//org.bouncycastle.math.ec.ECAlgorithms.implShamirsTrickWNaf(ECAlgorithms.java:344)
        at app//org.bouncycastle.math.ec.GLVMultiplier.multiplyPositive(GLVMultiplier.java:37)
        at app//org.bouncycastle.math.ec.AbstractECMultiplier.multiply(AbstractECMultiplier.java:15)
        at app//org.bouncycastle.math.ec.ECPoint.multiply(ECPoint.java:553)
        at app//org.bouncycastle.crypto.agreement.ECDHBasicAgreement.calculateAgreement(Unknown Source)
        at app//org.apache.tuweni.rlpx.RLPxConnectionFactory.forEncryption(RLPxConnectionFactory.java:248)
        at app//org.apache.tuweni.rlpx.RLPxConnectionFactory.encryptMessage(RLPxConnectionFactory.java:220)
        at app//org.apache.tuweni.rlpx.RLPxConnectionFactory.init(RLPxConnectionFactory.java:141)
        at app//org.apache.tuweni.rlpx.vertx.VertxRLPxService.lambda$connectTo$6(VertxRLPxService.java:327)
        at app//org.apache.tuweni.rlpx.vertx.VertxRLPxService$$Lambda$358/0x0000000800f9e040.apply(Unknown Source)
        at app//io.vertx.core.Future.lambda$map$4(Future.java:411)
        at app//io.vertx.core.Future$$Lambda$359/0x0000000800f9e440.handle(Unknown Source)
        at app//io.vertx.core.impl.SucceededFuture.onComplete(SucceededFuture.java:41)
        at app//io.vertx.core.Future.map(Future.java:407)
        at app//io.vertx.core.Future.map(Future.java:30)
        at app//org.apache.tuweni.rlpx.vertx.VertxRLPxService.lambda$connectTo$7(VertxRLPxService.java:324)
        at app//org.apache.tuweni.rlpx.vertx.VertxRLPxService$$Lambda$329/0x0000000800f87440.handle(Unknown Source)
        at app//io.vertx.core.net.impl.NetClientImpl.lambda$null$5(NetClientImpl.java:226)
        at app//io.vertx.core.net.impl.NetClientImpl$$Lambda$351/0x0000000800f98c40.handle(Unknown Source)
        at app//io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at app//io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at app//io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
        at app//io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
        at app//io.vertx.core.net.impl.NetClientImpl.lambda$connected$6(NetClientImpl.java:221)
        at app//io.vertx.core.net.impl.NetClientImpl$$Lambda$345/0x0000000800f81c40.handle(Unknown Source)
        at app//io.vertx.core.net.impl.VertxHandler.setConnection(VertxHandler.java:76)
        at app//io.vertx.core.net.impl.VertxHandler.handlerAdded(VertxHandler.java:93)
        at app//io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at app//io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at app//io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
        at app//io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
        at app//io.vertx.core.net.impl.NetClientImpl.connected(NetClientImpl.java:232)
        at app//io.vertx.core.net.impl.NetClientImpl.lambda$doConnect$3(NetClientImpl.java:187)
        at app//io.vertx.core.net.impl.NetClientImpl$$Lambda$330/0x0000000800f86c40.handle(Unknown Source)
        at app//io.vertx.core.net.impl.ChannelProvider.lambda$connect$1(ChannelProvider.java:78)
        at app//io.vertx.core.net.impl.ChannelProvider$$Lambda$331/0x0000000800f85c40.handle(Unknown Source)
        at app//io.vertx.core.net.impl.ChannelProvider.connected(ChannelProvider.java:160)
        at app//io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$2(ChannelProvider.java:143)
        at app//io.vertx.core.net.impl.ChannelProvider$$Lambda$336/0x0000000800f84440.operationComplete(Unknown Source)
        at app//io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at app//io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
```

**Comment by atoulme** [comment]
Moving to a worker thread might help. Queuing or maxing out active connections is a good idea too.

**Comment by atoulme** [comment]
Closing as we now limit to 50 max connections by default - can be reopened if we decide to allow more parallel connections.
